<?xml version="1.0" ?>
<robot name="tidybot" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find tidybot)/urdf/common_properties.xacro"/>
  <!-- <xacro:include filename="$(find tidybot)/urdf/robot_control.gazebo.xacro"/> -->
  <!-- <xacro:include filename="$(find tidybot)/urdf/robot_description_original.gazebo.xacro"/> -->

  <!-- Uncomment to disable the physics engine! -->

  <gazebo>
    <static>true</static>
  </gazebo>




  <!-- PROPERTIES -->
  <xacro:property name="base_offset_x" value="-0.064"/>
  <xacro:property name="base_offset_y" value="0.0"/>
  <xacro:property name="base_offset_z" value="0.0"/>

  <xacro:property name="base_length" value="0.266"/>
  <xacro:property name="base_width" value="0.266"/>
  <xacro:property name="base_height" value="0.0915"/>


  <xacro:property name="arm_base_length" value="0.0465"/>
  <xacro:property name="arm_base_width" value="0.0285"/>
  <xacro:property name="arm_base_height" value="0.036"/>

  <xacro:property name="link_offset_x" value="0.02275"/>


  <xacro:property name="first_link_length" value="0.028"/>
  <xacro:property name="first_link_width" value="0.038"/>
  <xacro:property name="first_link_height" value="0.0405"/>

  <xacro:property name="second_link_length" value="0.024"/>
  <xacro:property name="second_link_width" value="0.170"/>
  <xacro:property name="second_link_height" value="0.024"/>

  <xacro:property name="third_link_length" value="0.024"/>
  <xacro:property name="third_link_width" value="0.024"/>
  <xacro:property name="third_link_height" value="0.120"/>
    
  <xacro:property name="gripper_base_length" value="0.070"/>
  <xacro:property name="gripper_base_width" value="0.104"/>
  <xacro:property name="gripper_base_height" value="0.05825"/>

  <xacro:property name="finger_length" value="0.072"/>
  <xacro:property name="finger_width" value="0.016"/>
  <xacro:property name="finger_height" value="0.0536"/>
  <xacro:property name="finger_length_to_center" value="0.0395"/>
  
  <xacro:property name="finger_origin_offset" value="0.012"/>
  <xacro:property name="finger_offset_gripper_open" value="0.036"/>

  <xacro:property name="collision_box_reduction" value="0.02"/>
  


  <!-- ####################### -->


    <!-- ##################### BASE ################# -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.03" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/waffle_pi_base_for_open_manipulator.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.04575" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.0915"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0.0 0 0.0" rpy="0 0 0"/>
      <mass value="1.6329594e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />                
    </inertial>
  </link>

    <!-- ##################### WHEELS ################# -->
  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.7" friction="0.01"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>

  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -0.144 0.023" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
    <limit effort="100" velocity="100"/>
    <dynamics damping="0.7" friction="0.1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-02" />
      <inertia ixx="1.1175580e-05" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-05" iyz="-1.4400107e-11"
               izz="2.0712558e-05" />
      </inertial>
  </link>




  <!-- ##################### ARM BASE ################# -->

  <joint name="arm_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="arm_base_link"/>
    <origin xyz="${base_offset_x} 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="arm_base_link">
    <visual>
      <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/arm_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="-0.0120 0 ${arm_base_height / 2}" rpy="0 0 0"/>
      <geometry>
        <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.045438" />
      <inertia ixx="7196.83" ixy="2.068e-09" ixz="-129.011"
               iyy="12433.762" iyz="-2.775e-10"
               izz="11004.658" />
      </inertial>
  </link>


  <!-- ###################### FIRST LINK #####################-->
  <joint name="first_link_joint" type="continuous">
    <parent link="arm_base_link"/>
    <child link="first_link"/>
    <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="first_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/first_link.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${first_link_height / 2}" rpy="0 0 0"/>
      <geometry>
        <box size="${first_link_length - 0.001} ${first_link_width - 0.001} ${first_link_height / 2}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.060172" />
      <inertia ixx="21477.332" ixy="13.541" ixz="-430.792"
               iyy="21301.068" iyz="-111.614"
               izz="12348.458" />
      </inertial>
  </link>


  <!-- ##################### SECOND LINK ################# -->
  <joint name="second_link_joint" type="revolute">
    <parent link="first_link"/>
    <child link="second_link"/>
    <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100" lower="${-(pi)}" upper="${pi}"/>
    <dynamics damping="0.7" friction="0.01"/>

  </joint>

  <link name="second_link">
    <visual>
      <origin xyz="0 0 ${second_link_width}" rpy="${-(pi/2)} 0 ${pi/2}"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/link_170.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 ${second_link_width / 2}" rpy="${pi/2} 0 0"/>
      <geometry>
        <box size="${second_link_length} ${second_link_width - 0.04} ${second_link_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.112589" />
      <inertia ixx="3.509e+05" ixy="-61.351" ixz="-1202.759"
               iyy="3.432e+05" iyz="-36743.271"
               izz="38079.446" />
      </inertial>
  </link>






  <!-- ##################### THIRD LINK ################# -->
  <joint name="third_link_joint" type="revolute">
    <parent link="second_link"/>
    <child link="third_link"/>
    <origin xyz="0 0 ${second_link_width}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100" lower="${-(2*pi/3)}" upper="${2*pi/3}"/>
    <dynamics damping="0.7" friction="0.01"/>

  </joint>
  
  <link name="third_link">
    <visual>    
      <origin xyz="${third_link_height} 0 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/link_120.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="${third_link_height / 2} 0 0" rpy="0 ${pi/2} 0"/>
      <geometry>
        <box size="${third_link_length} ${third_link_width} ${third_link_height - collision_box_reduction}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.094954" />
      <inertia ixx="1.744e+05" ixy="647.52" ixz="-7.071"
               iyy="22596.123" iyz="-389.804"
               izz="1.803e+05" />
      </inertial>
  </link>

  <!-- ################## GRIPPER BASE ################### -->
  <joint name="gripper_base_joint" type="revolute">
    <parent link="third_link"/>
    <child link="gripper_base"/>
    <origin xyz="${third_link_height} 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100" lower="-${pi/2}" upper="${pi/2}"/>
    <dynamics damping="0.7" friction="0.01"/>

  </joint>
  
  <link name="gripper_base">
    <visual>    
      <origin xyz="0 0 0" rpy="0 0 ${-pi/2}"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/gripper_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="${gripper_base_length / 2} 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${gripper_base_length} ${gripper_base_width} ${gripper_base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.102503" />
      <inertia ixx="42037.078" ixy="0.002" ixz="-0.051"
               iyy="74712.63" iyz="1902.432"
               izz="61851.428" />
      </inertial>
  </link>

  <!-- ################# LEFT FINGER ################# -->
  <joint name="left_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="left_finger"/>
    <origin xyz="${gripper_base_length} ${finger_origin_offset + finger_offset_gripper_open} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100" lower="0" upper="${finger_origin_offset + finger_offset_gripper_open}"/>
    <dynamics damping="0.7" friction="1.0"/>

  </joint>
  
  <link name="left_finger">
    <visual>    
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/gripper_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="${finger_length / 2} ${-((finger_origin_offset / 2) - 0.002)} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.02010" />
      <inertia ixx="4734.61" ixy="700.053" ixz="22.926"
               iyy="12948.951" iyz="6.405"
               izz="8977.298" />
      </inertial>
  </link>


  <!-- ################# RIGHT FINGER ################# -->
  <joint name="right_finger_joint" type="prismatic">
    <parent link="gripper_base"/>
    <child link="right_finger"/>
    <origin xyz="${gripper_base_length} ${-(finger_origin_offset + finger_offset_gripper_open)} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="100" velocity="100" lower="${-(finger_origin_offset + finger_offset_gripper_open)}" upper="0"/>
    <dynamics damping="0.7" friction="1.0"/>

  </joint>
  
  <link name="right_finger">
    <visual>    
      <origin xyz="0 0 0" rpy="${pi} 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/gripper_finger.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="${finger_length / 2} ${(finger_origin_offset / 2) - 0.002} 0" rpy="0 0 0"/>
      <geometry>
        <box size="${finger_length} ${finger_width} ${finger_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.02010" />
      <inertia ixx="4734.61" ixy="700.053" ixz="22.926"
               iyy="12948.951" iyz="6.405"
               izz="8977.298" />
      </inertial>
  </link>




    <!-- ##################### CASTERS ################# -->
  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-0.177 -0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-0.177 0.064 -0.004" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.030 0.009 0.020"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.005" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

    <!-- ##################### SENSORS ################# -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.024 0 0.122" rpy="0 0 0"/> 
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0.02 0 -0.01" rpy="0 0 0"/>
      <geometry>
        <mesh filename="$(find tidybot)/meshes/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.032 0 -0.015" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.031" radius="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>
<!-- 
  <joint name="camera_joint" type="fixed">
    <origin xyz="0.073 -0.011 0.084" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <collision>
      <origin xyz="0.005 0.011 0.013" rpy="0 0 0"/>
      <geometry>
        <box size="0.015 0.030 0.027"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="0.003 0.011 0.009" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/> -->

</robot>
