controller_manager:
  ros__parameters:
    update_rate: 100  # H

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_control:
      type: forward_command_controller/ForwardCommandController


joint_trajectory:
  ros__parameters:
    joints:
      - first_link_joint
      - second_link_joint
      - third_link_joint
      - gripper_base_joint
      # ...

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity


gripper_control:
  ros__parameters:
    joints:
      - left_finger_joint # Only need the left joint as the right joint mimics it

    interface_name: position