controller_manager:
  ros__parameters:
    update_rate: 100  # H

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory:
      type: joint_trajectory_controller/JointTrajectoryController
    
    gripper_control:
      type: forward_command_controller/ForwardCommandController



joint_trajectory:
  ros__parameters:
    joints:
      - JOINT_NAME
      - JOINT_NAME
      # ...

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity



gripper_control:
  ros__parameters:
    joints:
      - JOINT_NAME

    interface_name: position
